In [4]:
import numpy as np 

In [6]:
array_from_grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
print(array_from_grades)

[85 90 88 92 95 80 75 98 89 83]


In [10]:
mean = np.mean(array_from_grades)
median = np.median(array_from_grades)
std_dev = np.std(array_from_grades)
print("Mean:", mean)
print("Median:", median) 
print("Standard Deviation:", std_dev) 

Mean: 87.5
Median: 88.5
Standard Deviation: 6.591661399070799


In [12]:
print("Minimum value using np.min: ",np.min(array_from_grades))
print("Maximum value using np.max: ",np.max(array_from_grades))

Minimum value using np.min:  75
Maximum value using np.max:  98


In [16]:
array_from_grades.sort()
print(array_from_grades)

[75 80 83 85 88 89 90 92 95 98]


In [20]:
index_of_highest_grade = np.argmax(array_from_grades)
print("Index of the highest grade:", index_of_highest_grade)

Index of the highest grade: 9


In [22]:
x = array_from_grades > 90
y =  np.sum(x)
print("Number of students who scored above 90:", y)

Number of students who scored above 90: 3


In [25]:
total_students = len(array_from_grades)
percentage_above_90 = (y / total_students) * 100
print("Percentage of students who scored above 90:", percentage_above_90, "%")

Percentage of students who scored above 90: 30.0 %


In [27]:
ux = array_from_grades < 75
uy = np.sum(ux)
total_students = len(array_from_grades)
xy = (uy / total_students) * 100
print("Percentage of students who scored below 75:", xy, "%")

Percentage of students who scored below 75: 0.0 %


In [30]:
high_performers = np.array([92, 95, 98])
print(high_performers)

[92 95 98]


In [34]:
passing_grades = np.array([80, 83, 85, 88, 89, 90, 92, 95, 98])
print(passing_grades)

[80 83 85 88 89 90 92 95 98]
